version: '3.8'

services:
  gateway:
    image: gateway-service-image
    container_name: gateway-service
    ports:
      - "${GATEWAY_PORT}:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=${ENV}
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
