version: '3.8'

services:
  authentificationService:
    build:
      context: .
      dockerfile: Dockerfile
    image: authentification-service-image
    container_name: authentification-service
    ports:
      - "8081:8080"
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
